// <auto-generated />
using System;
using AfvalMonitoring.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AfvalMonitoring.Migrations.DataDb
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20260608163906_RemoveUserNavigation")]
    partial class RemoveUserNavigation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AfvalMonitoring.Models.Analyses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Biodegradable")
                        .HasColumnType("int");

                    b.Property<int>("Cloth")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Glass")
                        .HasColumnType("int");

                    b.Property<int>("Metal")
                        .HasColumnType("int");

                    b.Property<int>("Paper")
                        .HasColumnType("int");

                    b.Property<int>("Plastic")
                        .HasColumnType("int");

                    b.Property<int>("TotaleAfval")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("AfvalMonitoring.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("AfvalMonitoring.Models.DataObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float?>("BoundingBoxCenterX")
                        .HasColumnType("real");

                    b.Property<float?>("BoundingBoxCenterY")
                        .HasColumnType("real");

                    b.Property<float?>("BoundingBoxLB")
                        .HasColumnType("real");

                    b.Property<float?>("BoundingBoxRB")
                        .HasColumnType("real");

                    b.Property<int>("CameraID")
                        .HasColumnType("int");

                    b.Property<float?>("Confidence")
                        .HasColumnType("real");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("LocatieAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocatieCoordinaten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("Tijd")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DataObjects");
                });

            modelBuilder.Entity("AfvalMonitoring.Models.Voorspelling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("All")
                        .HasColumnType("int");

                    b.Property<int>("Biodegradable")
                        .HasColumnType("int");

                    b.Property<int>("Cloth")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Glass")
                        .HasColumnType("int");

                    b.Property<int>("Metal")
                        .HasColumnType("int");

                    b.Property<int>("Paper")
                        .HasColumnType("int");

                    b.Property<int>("Plastic")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Voorspellingen");
                });
#pragma warning restore 612, 618
        }
    }
}
